name: serializable_example
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serializable:
    path: ../

dev_dependencies:
  build_runner: any
  test: any
  build_test: any
#  build_web_compilers: any
