targets:
  $default:
    builders:
      serializable:
        generate_for: [example/**, test/**]
      built_mirrors:
        generate_for:
          exclude: ['**']
builders:
  serializable:
    import: package:serializable/builder.dart
    builder_factories: [builder]
    auto_apply: dependents
    build_extensions:
      .dart: [.serializable.g.part]
    applies_builders: [source_gen|combining_builder]
