name: serializable
version: 0.7.0
description: generates a serializable class from classes using `source_gen` package
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/serializable

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  analyzer: ^0.30.0
  build: ^0.10.0
  source_gen: ^0.7.0
  build_runner: ^0.4.0
  built_mirrors: ^0.6.0
#  built_mirrors:
#    path: ../built_mirrors

dev_dependencies:
  test: ^0.12.0
  build_test: ^0.6.0
