name: serializable
version: 0.11.1
description: generates a serializable class from classes using `source_gen` package
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/serializable

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^0.33.0
  build: ^1.0.1
  source_gen: ^0.9.0
  serializable_core: ^0.11.1
#  serializable_core:
#    path: ../serializable_core

dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.1
  build_runner: ^1.0.0
