name: serializable
version: 1.0.0
description: generates a serializable class from classes using `source_gen` package
homepage: https://github.com/dart-league/serializable

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  analyzer: ^3.3.1
  build: ^2.2.1
  source_gen: ^1.2.1
  built_mirrors: ^1.0.0
#  built_mirrors:
#    path: ../built_mirrors

dev_dependencies:
  test: ^1.20.2
  build_test: ^2.1.5
  build_runner: ^2.1.8
