name: serializable
version: 2.0.1
description: generates a serializable class from classes using `source_gen` package
homepage: https://github.com/dart-league/serializable

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.0
  source_gen: ^1.3.2
  built_mirrors: ^2.0.1
  collection: ^1.17.2
#  built_mirrors:
#    path: ../built_mirrors

dev_dependencies:
  test: ^1.24.3
  build_test: ^2.1.7
  build_runner: ^2.4.4
