name: serializable
version: 0.13.0
description: generates a serializable class from classes using `source_gen` package
homepage: https://github.com/dart-league/serializable

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.36.0 <1.0.0'
  build: ^1.0.1
  source_gen: ^0.9.0
  built_mirrors: ^0.12.0
#  built_mirrors:
#    path: ../built_mirrors

dev_dependencies:
  test: ^1.0.0
  build_test: ^1.2.0
  build_runner: ^1.0.0
