name: serializable
version: 0.2.1
description: generates a serializable class from classes using `source_gen` package
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/serializable

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_mirrors: ^0.1.0
#  built_mirrors:
#    path: ../built_mirrors

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  build_test: ^0.4.0
